# -*- coding: utf-8 -*-
"""ALLERGY, COLD, COVID, FLU, .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HhO8kJX_sR8uIOoHSMRIyKpw5MIyTLHU

# Disease Prediction Based on Symptoms

## importing libs
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, roc_curve, auc
from sklearn.inspection import permutation_importance

"""## loading the dataset"""

data = pd.read_csv('small.csv')
data.head()

"""##  preprocessing"""

X = data.drop('TYPE', axis=1)
y = data['TYPE']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

"""## traning the random forest model first"""

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train_scaled, y_train)

"""## seeing the accuracy"""

y_pred = rf_model.predict(X_test_scaled)
accuracy = accuracy_score(y_test, y_pred)
print(f"Random Forest Accuracy: {accuracy:.2f}")

# Save the Random Forest model
import joblib

# Save the model
joblib.dump(rf_model, 'random_forest_model_for_flu_cold_covid_allergy.pkl')

# Save the scaler
joblib.dump(scaler, 'scaler.pkl')

print("Random Forest model and scaler have been saved successfully.")

# The rest of the code is commented out as per instructions

"""# once again random forest won and i got 97% accuracy"""